
trigger:
- main

pool: eventstorage

variables:
  buildConfiguration: 'Release'

jobs:
  - job: restore_and_build
    displayName: 'restore and build'

    steps:
      - task: UseDotNet@2
        displayName: install net8
        inputs:
          packageType: 'sdk'
          version: '8.0.x'

      - script: |
          dotnet restore
        displayName: 'restore'
        
      # - script: |
      #     dotnet build --no-restore --configuration $(buildConfiguration)
      #   displayName: 'restore'

      - task: DotNetCoreCLI@2
        displayName: 'build'
        inputs:
          command: 'build'
          projects: '**/*.csproj'
          arguments: '--no-restore'
          
          
  

