version: '3'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: asynchandler_mssql
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: sysadmin@2024
  postgres:
    image: postgres
    container_name: asynchandler_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
